### ISSUE TITLE
Excuse me, how can I debug "unexpected read from socket" if it occurs?

### ISSUE THREAD

**Issue by hxgdzyuyi** [thc2cat/go-policyd#3]
I found go-policyd while searching for how to handle "unexpected read from socket" error with go-mysql-driver.

I found "unexpected read from socket" in go-policyd's RREADME.md.

I'd like to ask you how you debug this error at that time, thank you.

**Comment by thc2cat** [comment]
Hello.

Db reconnection is done after db.Exec Failure by the db lib, 
when encountering db.Ping error, go-policyd respond DUNNO to avoid mail rejection due to database connection issue.

Connection is usualy lost when mariadb is upgraded and/or restarted.

        dberr := db.Ping()
	if dberr != nil {
		xlog.Err("Skipping policyVerify db.Ping Error: " + dberr.Error())
		// Ref : https://github.com/go-sql-driver/mysql/issues/921
		db.Exec("SELECT NOW()") // Generate an error for db recovery
		return "DUNNO"          // always return DUNNO on error
	}

**Comment by hxgdzyuyi** [comment]
thanks @thc2cat
